vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|09 Aug 2005 00:09:15 -0000
vti_extenderversion:SR|4.0.2.8912
vti_cacheddtm:TX|09 Aug 2005 00:09:15 -0000
vti_filesize:IR|24267
vti_cachedlinkinfo:VX|H|javascript:; S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/preview.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/fgcolor.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/hr.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/vertical_line.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/link.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/imagelink.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/image.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/table.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/htag.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/preview.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Cut.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Copy.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Paste.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/undo.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/redo.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/vertical_line.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Bold.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Italic.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/under.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/strikethrough.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Superscript.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Subscript.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/vertical_line.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/left.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Center.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/right.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/vertical_line.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/numlist.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/bullist.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/inindent.gif S|<%=SCRIPT_LIBRARY_PATH%>richtext/images/outdent.gif
vti_cachedsvcrellinks:VX|SHUS|javascript:; USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/preview.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/fgcolor.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/hr.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/vertical_line.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/link.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/imagelink.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/image.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/table.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/htag.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/preview.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Cut.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Copy.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Paste.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/undo.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/redo.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/vertical_line.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Bold.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Italic.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/under.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/strikethrough.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Superscript.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Subscript.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/vertical_line.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/left.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/Center.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/right.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/vertical_line.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/numlist.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/bullist.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/inindent.gif USUS|<%=SCRIPT_LIBRARY_PATH%>richtext/images/outdent.gif
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_backlinkinfo:VX|
